apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian
  template:
    metadata:
      labels:
        app: obsidian
    spec:
      containers:
      - name: obsidian
        image: lscr.io/linuxserver/obsidian:latest
        ports:
        - containerPort: 3000
        - containerPort: 3001
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
        - name: DISPLAY
          value: ":0"
        - name: XDG_RUNTIME_DIR
          value: "/tmp"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: x11-unix
          mountPath: /tmp/.X11-unix
        resources:
          requests:
            memory: "1Gi"
      volumes:
      - name: x11-unix
        hostPath:
          path: /tmp/.X11-unix
      - name: config-volume
        persistentVolumeClaim:
          claimName: obsidian-pvc
      restartPolicy: Always
