apiVersion: v1
kind: PersistentVolume
metadata:
  name: obsidian-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "."
