apiVersion: v1
kind: Service
metadata:
  name: obsidian-service
spec:
  selector:
    app: obsidian
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3001
